# Copyright © Siemens 2024 - 2025. ALL RIGHTS RESERVED.
# Licensed under the MIT license
# See LICENSE file in the top-level directory

# Define text of file header
inlineHeader = """
Copyright © ${copyrightOwner} ${hawkeye.git.fileCreatedYear} - ${hawkeye.git.fileModifiedYear}. ALL RIGHTS RESERVED.
Licensed under the MIT license
See LICENSE file in the top-level directory
"""
# You can exclude files and folders
excludes = [
]
# Define variables for your file header
[properties]
copyrightOwner = "Siemens"
# Activate git features to detect when a file has been changed
[git]
ignore = 'auto'
attrs = 'enable'
